services:
  postgres:
    image: postgres:16-alpine
    container_name: mpcis-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mpcis
      POSTGRES_PASSWORD: mpcis
      POSTGRES_DB: mpcis
    ports:
      - "5433:5432"
    volumes:
      - mpcis_pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: mpcis-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: mpcis
      MINIO_ROOT_PASSWORD: mpcisminio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - mpcis_minio_data:/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mpcis-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./infra/mosquitto/passwd:/mosquitto/config/passwd:ro
      - ./infra/mosquitto/acl:/mosquitto/config/acl:ro

  # SMTP dev catcher — UI http://localhost:8025 · SMTP :1025
  mailpit:
    image: axllent/mailpit:v1.22.3
    container_name: mpcis-mailpit
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mpcis_pg_data:
  mpcis_minio_data:
