# Staging / lab MQTTS
listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

listener 8883
protocol mqtt
cafile /mosquitto/certs/server.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl

persistence false
connection_messages false
log_dest stdout
log_type error
log_type warning
log_type notice
